export const projects = [
  {
    title: 'Technology news website',
    description: "This site is online publication that focuses on technology news, reviews, and analysis.",
    image: '/images/p1.jpg',
    tags: ['Node.js', 'Firebase', 'Next.js', 'Rest API'],
    source: 'https://github.com/sebastianpoez/',
    visit: 'https://canaltech.com.br/',
    id: 0,
  },
  {
    title: 'News and international trade website',
    description: "A website featuring news articles and forums related to international trade and customs.",
    image: '/images/p2.jpg',
    tags: ['Node.js', 'React', 'MongoDB', 'Restful API'],
    source: 'https://github.com/sebastianpoez/',
    visit: 'https://oficinadanet.com.br/',
    id: 1,
  },
  {
    title: 'Smartphone Website',
    description: "Online site for the latest smartphones from top brands.",
    image: '/images/p3.jpg',
    tags: ['React', 'Nest.js', 'MongoDb', 'Typescipt', 'Sass'], 
    source: 'https://github.com/sebastianpoez/',
    visit: 'https://futurecell.com.au/',
    id: 2,
  },
  {
    title: 'Business or cooporate website.',
    description: "ElectraBlue is a flash & forget custom kernel for supported Android devices. It was developed with the aim to provide a stable, fluid, & battery-efficient experience with customizations.",
    image: '/images/p4.jpg',
    tags: ['Express.js', 'MySQL', 'CSS5', 'Typescript'],
    source: 'https://github.com/sebastianpoez/',
    visit: 'https://oficinadanet.com.br/',
    id: 3,
  },
  {
    title: 'Lenovo SNAPit',
    description: "Lenovo SNAPit Camera was one of the finest OEM camera apps back in those days. It had tonnes of unique and amazing features. I ported it to work on almost all devices at that time.",
    image: '/images/p5.jpg',
    tags: ['Node.js', 'Firebase', 'TailwindCSS', 'Typescript'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
    id: 3,
  },
  {
    title: 'CyanogenOS Apps',
    description: "CyanogenOS 12.1 had a set of exclusive apps like a new theme engine and a new Truecaller integrated dialer. I ported it to work with CyanogenMod 13 and CM 13 based ROMs.",
    image: '/images/p6.jpg',
    tags: ['Nest.js', 'MongoDB', 'CSS5', 'Typescript'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    id: 3,
  },

];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a developer.', },
  { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
  { year: 2018, text: 'Learned Android app development.', },
  { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  { year: 2020, text: 'Aquired new skills while trying not to catch COVID-19', },
  { year: 2021, text: 'Survived COVID-19 and got my first Job at Primebook.', },
  { year: 2022, text: 'Completed B.Tech in Information Technology.', },
  { year: 2023, text: 'Year under progress....', },
];